# Generated by Django 5.2.2 on 2026-02-23 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_resumeanalysis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
