# Generated by Django 5.2.2 on 2026-02-25 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_delete_resume'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('skills', models.TextField(help_text='Comma separated skills')),
                ('experience', models.TextField(help_text='Describe work experience')),
                ('projects', models.TextField(help_text='Describe projects')),
                ('education', models.TextField(help_text='Education details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='job_score',
            new_name='experience_score',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='responsibility_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='skill_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
