# Generated by Django 5.2.2 on 2026-03-09 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0004_resume_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='experience_score',
            new_name='impact_score',
        ),
        migrations.RenameField(
            model_name='resumeanalysis',
            old_name='responsibility_score',
            new_name='keyword_score',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='created_at',
        ),
        migrations.AddField(
            model_name='resume',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='other_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='resume_photos/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='template_choice',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('two_column', 'Two Column'), ('minimal', 'Minimal'), ('professional', 'Professional')], default='modern', max_length=50),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='section_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='semantic_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='job_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='resumeanalysis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
