# Generated by Django 5.2.2 on 2026-03-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0005_rename_experience_score_resumeanalysis_impact_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysis',
            name='job_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='responsibility_score',
            field=models.IntegerField(default=0),
        ),
    ]
